// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgwrapper/response.proto

package msgwrapper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	// 状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	// 提示信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	// 详情
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail"`
	// 数据体
	Data                 *any.Any `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_7b92cd7d71f3c890, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Response) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "msgwrapper.Response")
}

func init() { proto.RegisterFile("msgwrapper/response.proto", fileDescriptor_response_7b92cd7d71f3c890) }

var fileDescriptor_response_7b92cd7d71f3c890 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8d, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x45, 0x89, 0xd6, 0xaa, 0xe3, 0x2e, 0x88, 0xa4, 0xae, 0x8a, 0xab, 0xac, 0x52, 0xd0, 0x13,
	0x78, 0x85, 0xdc, 0x60, 0x6a, 0xc7, 0x20, 0xb4, 0x9d, 0x90, 0x54, 0xa4, 0x9e, 0x5e, 0x48, 0x5b,
	0xdc, 0xcd, 0x9f, 0xf7, 0x3f, 0x0f, 0x8a, 0x2e, 0xba, 0x4f, 0x40, 0xef, 0x29, 0x54, 0x81, 0xa2,
	0xe7, 0x3e, 0x92, 0xf1, 0x81, 0x07, 0x96, 0xf0, 0x47, 0xe7, 0xc2, 0x31, 0xbb, 0x96, 0xaa, 0x44,
	0xea, 0xf7, 0xb3, 0xc2, 0x7e, 0x9c, 0x6a, 0x97, 0x2f, 0xec, 0xec, 0x3c, 0x94, 0x12, 0xb2, 0x07,
	0x37, 0xa4, 0x44, 0x29, 0xf4, 0xc6, 0xa6, 0x5b, 0x2a, 0xd8, 0x76, 0x14, 0x23, 0x3a, 0x52, 0xab,
	0x52, 0xe8, 0xbd, 0x5d, 0xa2, 0x3c, 0x41, 0xde, 0xd0, 0x80, 0xaf, 0x56, 0xad, 0x13, 0x98, 0x93,
	0xd4, 0x90, 0x35, 0x38, 0xa0, 0xca, 0x4a, 0xa1, 0x0f, 0xd7, 0xa3, 0x99, 0xdc, 0x66, 0x71, 0x9b,
	0x7b, 0x3f, 0xda, 0xd4, 0xa8, 0xf3, 0xf4, 0xbb, 0xfd, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x32,
	0xdb, 0xbb, 0xc6, 0x00, 0x00, 0x00,
}
